### ISSUE TITLE
Ability to specify lintrc file

### ISSUE THREAD

**Issue by ZachStoltz** [rogeliog/jest-runner-eslint#11]
Hello,

First off, AWESOME job!  Just implemented this and had a jaw dropping moment of how fast the linting is for our CI.

Is it possible to specify a specific .eslintrc file to run the jest-runner with?

Our scenario is:

 - Legacy linting from jshint converted to eslint
 - CI is ran via this eslintrc file via gulp (.lintrc)
 - Dev IDEs are running off of the root level .eslintrc extending AirBnB's style guide to allow us to slowly convert to the new styleguide we have in place.

I would like to be able to pass in said .lintrc to be able to use the needed linting rules for our CI.  Thoughts?

**Comment by rogeliog** [comment]
Hi! Thanks for reporting! 


We need to add a way for adding customization. I think this relates to #10
